config/routes.rb
IteamApp::Application.routes.draw do
  resources :approvers

  resources :monitor_items
  resources :project_users
  resources :addr_books
  resources :monitor_actions

  get "monitor/index"

  resources :servers
  resources :addr_books
  resources :links
  resources :documents
  resources :members
  resources :teams
  resources :categories
  resources :announcements

  get "pages/home"
  get "pages/contact"
  get "faq/index"
  match '/pages/daprotocol' => 'pages#daprotocol'
  match '/faq/direct_link' => 'faq#direct_link'
  match '/faq/recent_posts' => 'faq#recent_posts'
  match '/faq/change_parent' => 'faq#change_parent'
  match '/faq/get_categories' => 'faq#get_categories'
  match '/faq/get_selections' => 'faq#get_selections'
  match '/faq/get_answer' => 'faq#get_answer'
  match '/faq/new_answer' => 'faq#new_answer'
  match '/faq/search' => 'faq#search'
  match '/faq/post-question' => 'faq#post_question'
  match '/faq/answer_feedback' => 'faq#answer_feedback'
  match '/category/my_categories' => 'categories#my_categories'
  match '/announcements/send_email' => "announcements#send_email"
  match 'answer/tup_change' => "answers#tup_change"
  match 'monitor_action/new' => "monitor_actions#new"
  match 'monitor_action/index' => "monitor_actions#index"
  match '/monitor_item/perform' => "monitor_items#perform"
  match '/project_users/send_request_email' => "project_users#send_request_email"
  match '/project_users/send_completed_email' => "project_users#send_completed_email"
  match '/project_users/send_approved_email' => "project_users#send_approved_email"
  match '/project_users/send_denied_email' => "project_users#send_denied_email"
  match '/get_sponsors' => "project_users#get_sponsors"

  root :to => "pages#home"

end

app/controllers/faq_controller.rb
class FaqController < ApplicationController

  def index
    @teams = Team.find(:all, :order => "name")
    @keywords = Keyword.all(:select => 'distinct(content)', :limit => 20)

    # if someone comes in with a direct link to a post, show it
    if params[:name] == "question"
      if !params[:id].nil?
        @questions = Question.where(:id => params[:id])
      end
    else
      @questions = Question.find(:all, :order => 'created_at DESC', :limit => 5)
    end
    @categories = Array.new
  end

  def new_answer
    @qid = params[:qid]
    if !params[:submit].nil?
      answer = params[:answer]
      Answer.create!(:content => answer, :question_id => @qid, :user => session[:idsid])
      @answers = Question.find_by_id(@qid).answers.order("created_at")
      render :partial => 'answers'
    else
      render :partial => 'answer_form'
    end
  end

  def get_categories
    @teams = Team.all
    team_id = params[:team_id]
    #@categories = Team.find_by_id(team_id, :order => "name").categories
    @categories = Category.find(:all, :conditions => ["team_id = ?", team_id], :order => "name")
    render :partial => 'categories'
  end

  def get_selections
    @category_id = params[:category_id]
    @questions = Category.find_by_id(@category_id).questions
    render :partial => 'show_results'
    #@questions = @questions.paginate(:page => params[:page], :per_page => 6)
  end

  def recent_posts
    @questions = Question.find(:all, :conditions => ["created_at > ?", 7.days.ago], :order => 'created_at DESC')
    render :partial => 'show_results'
  end

  def direct_link
    type = params[:name]
    if type.eql?"question"
      qid = params[:id]
      @questions = Question.where(:id => qid)
    end
    #render :partial => 'show_results'
    render :text => 'This feature is not yet operational. Please check back later..'
  end

  def change_parent
    team_id = params[:team_id]
    @category_id = params[:category_id]
    qid = params[:qid]
    question = Question.find(qid)
    question.update_attribute(:category_id, @category_id)
    @questions = Category.find_by_id(@category_id).questions
    render :partial => 'show_results'
    #@questions = @questions.paginate(:page => params[:page], :per_page => 6)
  end

  def get_answer
    @qid = params[:qid]
    @answers = Question.find_by_id(@qid).answers
    render :partial => 'answers'
  end

  def post_question
    title = params[:title]
    answer = params[:content]
    team_id = params[:team_id]
    @category_id = params[:cat_id]
    category = Category.find(@category_id)

    q = Question.create!(:content => title, :user => session[:idsid], :category_id => @category_id)
    if(!answer.eql?"")
      a = Answer.create!(:content => answer, :user => session[:idsid], :question_id => q.id)
    end
    @questions = category.questions

    # send the new post email to the category owner
    Appmailer.new_post(category.owner, category.name, session[:idsid], title).deliver

    render :partial => 'show_results'
  end

  def search
    query = params[:search]
    @search = 1
    @keywords = Keyword.all(:select => 'distinct(content)', :limit => 30)
    @questions = Question.search query, :match_mode => :boolean
    if(@questions.count > 0)
      Keyword.create!(:content => query)
    end

    #@search = Question.search do
    #  fulltext query
    #end
    #@questions = @search.results
    render :partial => 'show_results'
  end

  def answer_feedback
    feed = params[:feed]
    ans_id = params[:id]
    if feed.to_i == 1
      val = Answer.find_by_id(ans_id).tup
      val += 1
      Answer.find_by_id(ans_id).update_attributes(:tup => val)
    else
      val = Answer.find_by_id(ans_id).tdown
      val += 1
      Answer.find_by_id(ans_id).update_attributes(:tdown => val)
    end
    render :nothing => true
  end

end

app/views/faq/_answer_form.html.erb
<ul>
 <li>Got an alternate answer? Or further information to improve this answer? Feel free to add here. Please do not use this space for providing feedback.
  <% form_tag %>
  <%= text_area :ans, @qid, :rows => 8, :cols => 60, :class => "new-answer", :maxlength => "1040" %><br />
  <div id="answer-chars" class="char-countdown">max characters allowed: 1040</div>
  <table class="answer-options">
    <tr>
      <td><%= link_to "Submit", "#", :name => @qid, :class => "add-answer" %></td>
      <td><%# link_to "Hide", '#', :class => "new-answer-req", :name => @qid %></td>
    </tr>
  </table>
 </li>
</ul>

app/views/faq/_answers.html.erb
<ul>
<% @answers.each do |answer| %>
    <%# link_to image_tag('attachment.png', :border => 0), answer.attachment.url, :target => '_blank' %>
    <li answer-id="<%= answer.id%>">
      <span class="faint-display">answer posted: <%= answer.created_at %>, by user: <%= answer.user %></span>
      <%= simple_format answer.content %>
      <span class="faint-display"><% if !answer.attachment_file_name.nil? %>Attachment: <%= link_to answer.attachment_file_name, answer.attachment.url, :target => "_blank" %><br /><% end %></span>
      <span class="ans-feedback">
        <%= link_to image_tag('tup.png', :border => 0), "#", :class => "tup", :title => "You like this answer" %>
        <%= link_to image_tag('tdown.png', :border => 0), "#", :class => "tdown", :title => "You don't like this answer" %>
      </span>
    </li>
    <hr />
  <% end %>
</ul>
<%= render 'answer_form' %>


<!--Did this reply help? (<%= link_to 'Yes', '#', :class => "tup" %> / <%= link_to 'No', '#', :class => "tdown" %>)-->

app/views/faq/_categories.html.erb
<%= collection_select(:category, :id, @categories, :id, :name, options ={:prompt => "Select a Category"}, :class => "select") %>

app/views/faq/_question_form.html.erb
<%= text_area :que, :text, :rows => 4, :cols => 40, :maxlength => 140 %><br />
<div class="charsRemaining"></div>
<%= link_to "Submit", "#", :class => "new-question" %>

app/views/faq/_show_results.html.erb
<% if @questions.count == 0 %>
    <div class="no-results">No matching results were found</div>
<% else %>
    <% @questions.each do |question| %>
        <span class="heading-text"><%= question.content %></span>

        <% if question.answers.count > 0 %>
          (<%= link_to pluralize(question.answers.count, 'answer'), "#", :class => "show-answers", :qid => question.id %>)
        <% else %>
          <span class="answer-count">(<%= pluralize(question.answers.count, 'answer') %>)</span>
        <% end %>

        <% # you never want to do this in a view but there was no other way %>
        <% question.answers.each do |a| %>
          <% if !a.attachment_file_name.nil? %>
            <%= image_tag("attachment.png", :alt => "attachments", :title => "answers have attachments") %>
            <% break %>
          <% end %>
        <% end %>
        <% if !Category.find_by_id(@category_id).nil? %>
          <% if Category.find_by_id(@category_id).has_owner?(session[:idsid]) %>
            <%= link_to image_tag("edit-icon.png", :alt => "edit", :title => "edit question"), edit_category_path(@category_id) %>
            <%= link_to image_tag("change.jpg", :alt => "change-parent", :title => "change team/category of question"), '#', :class => "change-parent", :id => question.id %>
          <% end %>
        <% end %>
        <%= link_to image_tag("link.png", :alt => "link", :title => "send someone a link to this question"), "#", :id => question.id, :class => "show-link" %>
        <% if question.answers.count == 0 %>
          <span><%= link_to "+a", '#', :class => "new-answer-req", :name => question.id %></span>
        <% end %>
        <div id="link-div_<%= question.id %>" class="link-div" style="display: none;"></div>
        <div class="faint-display">
          discussion posted: <%= question.created_at.strftime("%m-%d-%Y") %>, category: <%=h Category.find_by_id(question.category_id).name %>
            , team: <%=h Team.find_by_id(Category.find_by_id(question.category_id).team_id).name %>, posted by: <%= question.user %>
        </div>
        <div id="answer_<%= question.id %>" class="answers"></div><br />
    <% end %>

    <%# will_paginate @questions %>
<% end %>

app/views/faq/index.html.erb
<%= stylesheet_link_tag 'jquery-ui' %>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/jquery-ui.min.js"></script>
<script type="text/javascript" src="/ckeditor/ckeditor.js"></script>

<script type="text/javascript">

$(document).ready(function() {

  var change_q_parent = 0;
  var change_question_id = 0;

  $.ajaxSetup({
     key: 'value'
  });

  $(function() {
      $.ajaxSetup({
          error: function(jqXHR, exception) {
              if (jqXHR.status === 0) {
                  alert('Not connect.\n Verify Network.');
              } else if (jqXHR.status == 404) {
                  alert('Requested page not found. [404]');
              } else if (jqXHR.status == 500) {
                  alert('Internal Server Error [500].');
              } else if (exception === 'parsererror') {
                  alert('Requested JSON parse failed.');
              } else if (exception === 'timeout') {
                  alert('Time out error.');
              } else if (exception === 'abort') {
                  alert('Ajax request aborted.');
              } else {
                  alert('Uncaught Error.\n' + jqXHR.responseText);
              }
          }
      });
  });

  $("#question-form").dialog({
    autoOpen: false,
    modal: true,
    width: 450,
    buttons: {
      "Add": function() {
        var title = $("#newtitle").val().replace(/\'/g,'\\\'').replace(/"/g, '&quot;').replace(/\u0000/g, "\\0");
        var content = $("#newcontent").val().replace(/\'/g,'\\\'').replace(/"/g, '&quot;').replace(/\u0000/g, "\\0");
        //.replace(/\n/g, '<br \\>');
        //replace(/\'/g,'\\\'').replace(/"/g, '&quot;').replace(/\u0000/g, "\\0");
        var team_id = $('select#team_id :selected').val();
        var cat_id = $('select#category_id :selected').val();

        if(title == ""){
            alert("Title cannot be blank");
            $('#newtitle').focus();
            return false;
        }
        $.get('/faq/post-question?title=' + title + '&content=' + content + '&team_id=' + team_id + '&cat_id=' + cat_id , function(data){
          alert("Thanks, your entry was successfully submitted");
          $("#show-results").html(data);
        });
        $(this).dialog("close");
      },
      Cancel: function() {
        $(this).dialog("close");
      }
    }
  });

  $("#post-question").live("click", (function() {
    var team_id = $('select#team_id :selected').val();
    var cat_id = $('select#category_id :selected').val();
    if(team_id == "" || cat_id == "" || team_id == null || cat_id == null){
        alert("To post a new discussion, first select a team and category from the menu on the left")
        return false;
    }
    $("#question-form").dialog("open");
      // prevent the default action, e.g., following a link
      return false;
  }));


  $('#newtitle').live("keyup", (function(){
      var max = parseInt($(this).attr('maxlength'));
      if($(this).val().length > max){
          $(this).val($(this).val().substr(0, $(this).attr('maxlength')));
      }
      $('#new-content').html('(title) characters remaining: ' + (max - $(this).val().length));
  }));

  $('#newcontent').live("keyup", (function(){
      var max = parseInt($(this).attr('maxlength'));
      if($(this).val().length > max){
          $(this).val($(this).val().substr(0, $(this).attr('maxlength')));
      }
      $('#new-content').html('(content) characters remaining: ' + (max - $(this).val().length));
  }));

    $("#recent-posts").click(function() {
      jQuery.get('/faq/recent_posts', function(data){
          $("#show-results").html(data);
      })
      return false;
    });


  $("#team_id").change(function() {
    var team_id = $('select#team_id :selected').val();
    if(team_id == ""){
        alert('Select a Team');
        return false;
    }
    //$("#show-results").html("")
    jQuery.get('/faq/get_categories?team_id=' + team_id, function(data){
        $("#categories").html(data);
    })
    return false;
  });

  $("#category_id").live("change", (function() {
    var tid = $('select#team_id :selected').val();
    var cid = $('select#category_id :selected').val();

    // check to see if category has been selected to change the parent
    // of a question or to get content for a category
    if(change_q_parent == 1){
      if(confirm("Confirm move..")){
        jQuery.get('/faq/change_parent?team_id=' + tid + '&category_id= ' + cid + '&qid=' + change_question_id, function(data){
          change_q_parent = 0;
          $(".parent-change-message").toggle();
          $("#show-results").html(data);
          alert("Question moved. Displaying content for selected category");
        });
      }
      else{
          return false;
      }
      return false;
    }

    jQuery.get('/faq/get_selections?team_id=' + tid + '&category_id= ' + cid, function(data){
      $("#show-results").html(data);
    });
    return false;
  }));

  $(".change-parent").live("click", function() {
    change_question_id = $(this).attr("id");
    change_q_parent = 1;
    $(".parent-change-message").toggle();
  });

  $(".show-link").live("click", function() {
    var qid = $(this).attr("id");
    var url = $(location).attr('href');
    url = "http://scyweb05.sc.intel.com:3005/faq/index?name=question&id=" + qid;
    url = "<a href='"+url+"' target=_blank>"+url+"</a>";
    $("#link-div_" + qid).html(url);
    $("#link-div_" + qid).toggle();
    //$("#show-link").html("Copy-paste this url: " + url);
    //$("#show-link").dialog("open");
    // prevent the default action, e.g., following a link
    return false;
  });

  /*
  $("#show-link").dialog({
    autoOpen: false,
    modal: true,
    width: 450,
    buttons: {
      Cancel: function() {
        $(this).dialog("close");
      }
    }
  });
  */

  $(".search").live("click", (function() {
    //var q = $('#search').val().trim();
    var q = $('#search').val();
    if(q == ""){
        //$(".keyword-error-msg").html("enter one or more keyword(s)");
        return false;
    }
    jQuery.get('/faq/search?search=' + q, function(data){
        $(".keyword-error-msg").html("");
        $("#show-results").html(data);
    })
    return false;
  }));

  $(".tup").live("click", function() {
    var self = $(this);
    var ans_id = self.parent().parent().attr("answer-id");
    $.get("/faq/answer_feedback?feed=1&id=" + ans_id, function() {
        self.parent().html("Thanks, appreciate the feedback");
    });
  });

  $(".tdown").live("click", function() {
    var self = $(this);
    var ans_id = self.parent().parent().attr("answer-id");
    $.get("/faq/answer_feedback?feed=0&id=" + ans_id, function() {
        self.parent().html("Thanks, appreciate the feedback");
    });
  });

  $(".show-answers").live("click", (function() {
    var qid = $(this).attr("qid");
    jQuery.get('/faq/get_answer?qid=' + qid, function(data){
      $("#answer_" + qid).toggle("slow", function(){
        $("#answer_" + qid).html(data);
      });
    });
    return false;
  }));

  $('.new-answer').live("keyup", (function(){
      var max = parseInt($(this).attr('maxlength'));
      if($(this).val().length > max){
          $(this).val($(this).val().substr(0, $(this).attr('maxlength')));
      }
      $('#answer-chars').html('characters remaining: ' + (max - $(this).val().length));
  }));

    $(".new-answer-req").live("click", (function() {
      var qid = $(this).attr("name");
      jQuery.get('/faq/new_answer?qid=' + qid, function(data){
          // if  the answers are already being displayed
          if($("#answer_" + qid).css("display") == "block"){
              $("#answer_" + qid).append(data);
          }
          else{
              $("#answer_" + qid).toggle("slow", function(){
                  $("#answer_" + qid).html(data);
              });
          }
      });
      return false;
    }));

  $(".add-answer").live("click", (function() {
    var qid = $(this).attr("name");
    var answer = $('#ans_' + qid).val().replace(/\'/g,'\\\'').replace(/"/g, '&quot;').replace(/\u0000/g, "\\0");
    answer = jQuery.trim(answer);

    if(answer == ""){
        $('#ans_' + qid).focus();
        return false;
    }
    jQuery.get('/faq/new_answer?submit=1&qid=' + qid + '&answer=' + answer, function(data){
      $("#answer_" + qid).html(data);
    });
    return false;
  }));

  /*
  $("#post-question").live("click", (function() {
    var team_id = $('select#team_id :selected').val();
    var cat_id = $('select#category_id :selected').val();
    //alert(team_id + ", " + cat_id);
    if(team_id == "" || cat_id == "" || team_id == null || cat_id == null){
        alert("To post a question, first select a team and category from the menu on right")
        return false;
    }
    $(".show-question").toggle("slow", function(){
        $(".show-question").html("<%= escape_javascript(render(:partial => 'question_form')) %>")
        return false;
    })
  }));


  $(".new-question").live("click", (function() {
    var team_id = $('select#team_id :selected').val();
    var cat_id = $('select#category_id :selected').val();
    //alert(team_id + ", " + cat_id);
    var qtext = $('#que_text').val();
    if(qtext == ""){
        alert("You cannot submit a blank question");
        $('#que_text').focus();
        return false;
    }
    jQuery.get('/faq/post-question?que=' + qtext + '&team_id=' + team_id + '&cat_id=' + cat_id , function(data){
      $(".show-question").html("Thanks, your question has been noted and the appropriate category owner will be notified");
    });
    return false;
  }));

  */

  $("#show-keywords").live("click", (function() {
    $(".search-keywords").toggle();
  }));
});

</script>

<%# image_tag("faq.jpg", :alt => "DA FAQ", :class => "round") %>
<p>logged in as <b><%= get_first_name(session[:idsid]) %></b>..<br /><%# request.headers %>
<table class="faq-search">
  <tr>
    <td class="search-category2" colspan="2">Select Team and Category to view posts</td>
    <td class="search-separator">&larr; or &rarr;</td>
    <td class="search-category1">Perform a keyword search <%= link_to '(recent keywords)', '#', :id => "show-keywords" , :class => 'quick-links' %></td>
  </tr>
  <tr>
    <td class="search-options">
      <% form_tag('/faq/get_categories', :remote => true) do %>
        <%= collection_select(:team, :id, @teams, :id, :name, options ={:prompt => "Select a team"}, :class => "select") %><br />
      <% end %>
    </td>
    <td class="search-options">
      <div id="categories"></div>
    </td>
    <td class="search-options"></td>
    <td class="search-options">
      <% form_tag('/faq/search', :remote => true) do%>
        <%= text_field_tag :search, params[:search], :size => 50 %>
        <%= submit_tag "search", :class => 'search' %>
      <% end %>
    </td>
  </tr>
  <tr>
    <td colspan="2">
      <div class="parent-change-message" style="display: none;">
        Select the team and category you wish to move the question to
      </div>
    </td>
    <td></td>
    <td>
      <div class="search-keywords" style="display: none;">
        <% @keywords.each do |k| %>
            <%= "#{k.content}, " %>
        <% end %>
      </div>
    </td>
  </tr>
</table>
<p class="page-menu">
    <%= link_to 'Manage Teams', teams_path %> |
    <%= link_to 'Manage Categories', categories_path %> |
    <%= link_to 'My Categories', '/category/my_categories' %> |
    <%= link_to 'Post new discussion', '#', :id => "post-question" %> |
    <%= link_to 'Recent Posts', '#', :id => "recent-posts" %>
</p>
<div id="show-results">
  <%= render :partial => 'show_results' %>
</div><br />
<div id="question-form" title="Post a new discussion">
  To avoid duplicate discussion topics, please first check (via search) to see if no similar topics/discussions exist.
  <%= form_tag do %>
      <table>
       <tr>
         <td><%= label_tag(:s, "Title:") %></td>
         <td><%= text_area_tag "newtitle", "",  :rows => 3, :cols => 42, :maxlength => 140 %><span class="quick-links">(max length: 140)</span></td>
       </tr>
       <tr>
         <td><%= label_tag(:m, "Content:") %></td>
         <td><%= text_area_tag "newcontent", "", :rows => 10, :cols => 42, :maxlength => 1040 %><span class="quick-links">(max length: 1040)</span></td>
       </tr>
     </table>
  <% end %>
  <div id="new-content" class="char-countdown"></div>
</div>

