config/routes.rb
IteamApp::Application.routes.draw do
  resources :approvers

  resources :monitor_items
  resources :project_users
  resources :addr_books
  resources :monitor_actions

  get "monitor/index"

  resources :servers
  resources :addr_books
  resources :links
  resources :documents
  resources :members
  resources :teams
  resources :categories
  resources :announcements

  get "pages/home"
  get "pages/contact"
  get "faq/index"
  match '/pages/daprotocol' => 'pages#daprotocol'
  match '/faq/direct_link' => 'faq#direct_link'
  match '/faq/recent_posts' => 'faq#recent_posts'
  match '/faq/change_parent' => 'faq#change_parent'
  match '/faq/get_categories' => 'faq#get_categories'
  match '/faq/get_selections' => 'faq#get_selections'
  match '/faq/get_answer' => 'faq#get_answer'
  match '/faq/new_answer' => 'faq#new_answer'
  match '/faq/search' => 'faq#search'
  match '/faq/post-question' => 'faq#post_question'
  match '/faq/answer_feedback' => 'faq#answer_feedback'
  match '/category/my_categories' => 'categories#my_categories'
  match '/announcements/send_email' => "announcements#send_email"
  match 'answer/tup_change' => "answers#tup_change"
  match 'monitor_action/new' => "monitor_actions#new"
  match 'monitor_action/index' => "monitor_actions#index"
  match '/monitor_item/perform' => "monitor_items#perform"
  match '/project_users/send_request_email' => "project_users#send_request_email"
  match '/project_users/send_completed_email' => "project_users#send_completed_email"
  match '/project_users/send_approved_email' => "project_users#send_approved_email"
  match '/project_users/send_denied_email' => "project_users#send_denied_email"
  match '/get_sponsors' => "project_users#get_sponsors"

  root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", pages_home_path %></li>
      <li><%= link_to "Team", members_path %></li>
      <li><%= link_to "DADesk", '/faq/index' %></li>
      <li><%= link_to "Links", '/links'%></li>
      <li><%= link_to "Documents", '/documents'%></li>
      <li><%= link_to "Announcements", announcements_path %></li>
      <li><%= link_to "Project Access", project_users_path %></li>
      <% if session[:admin].present? %>
        <li><%= link_to "Monitoring", '/monitor/index' %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("iteam.jpg", :alt => "Sample App", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", pages_home_path %></li>
      <li><%= link_to "DADesk", '/faq/index' %></li>
      <!--<li><= link_to "Help", '#' %></li>  -->
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'jquery.cluetip' %>
    <%= javascript_include_tag 'jquery','rails', 'application.jquery', 'jquery.cluetip', :ckeditor, 'jquery.jeditable' %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>